
apiVersion: v1
kind: Namespace
metadata:
  name: crane-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: crane-manager
  namespace: crane-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crane-manager
  namespace: crane-system
  labels:
    app: crane-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crane-manager
  template:
    metadata:
      labels:
        app: crane-manager
    spec:
      serviceAccountName: crane-manager
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: crane-manager
          image: ccr.ccs.tencentyun.com/kube-orm/manager:latest
          imagePullPolicy: IfNotPresent
          command:
            - /manager
            - -v=4
