# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Crane - Cloud Resource Analytics and Economics
theme:
  name: material
#  custom_dir: overrides
  language: en
  features:
    - content.code.annotate
    - navigation.top
  palette:
    primary: blue
  logo: images/crane.svg
  favicon: images/crane.svg
  font:
    text: Work Sans
extra_javascript:
  - assets/util.js
extra_css:
  - assets/util.css
extra:
  version:
    provider: mike
    default: latest
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        zh:
          name: 简体中文
          build: true
      nav_translations:
        zh:
          Getting Started: 从这里开始
          Introduction: 介绍
          Installation: 安装
          Tutorials: 教程
          Proposals: 提案
          Contributing: 贡献
          Mirror Repo: 镜像仓库
          Code Standard: 代码标准
          Roadmap: 路线图
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/gocrane/crane
repo_name: gocrane/crane
nav:
  - Getting Started:
      - Introduction: index.md
      - Installation: installation.md
  - Tutorials:
      - Effective HPA: tutorials/using-effective-hpa-to-scaling-with-effectiveness.md
      - Analytics and Recommendation:
        - Resource Recommendation: tutorials/resource-recommendation.md
        - HPA Recommendation: tutorials/hpa-recommendation.md
      - Qos Ensurance: tutorials/using-qos-ensurance.md
      - Time Series Prediction: tutorials/using-time-series-prediction.md
      - Load-aware Scheduling: tutorials/scheduling-pods-based-on-actual-node-load.md
  - Proposals:
      - Advanced CpuSet Manager: proposals/20220228-advanced-cpuset-manger.md
  - Contributing: CONTRIBUTING.md
  - Code Standard: code-standards.md
  - Roadmap:
    - 1H 2022: roadmaps/roadmap-1h-2022.md
  - Mirror Repo: mirror.md
