
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: crane-mutating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNuRENDQVlRQ0NRQ0xMd1gzK09aUjdUQU5CZ2txaGtpRzl3MEJBUXNGQURBUU1RNHdEQVlEVlFRRERBVmoKY21GdVpUQWVGdzB5TWpBeU1UY3dPRFEyTlRSYUZ3MHpNakF5TVRVd09EUTJOVFJhTUJBeERqQU1CZ05WQkFNTQpCV055WVc1bE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdm84M25rK1I3eHZXCk15eUE5ZHRTa0RQVUxqcjJSMWVuSFlYaW1JNllDa2pxbWJ3QmQ4enFwNVhPWFNOTEVITW55dWpsaFc0bUJUK2YKUDBsZytoMlVzak5XWTFUQzBUTklyYVNSWmFkd0hlQkhaSEsvM2ZwTlllaDBoTXU3QWFUdmpiYWo4VmZyMGk1TwovL0RHVU5HcjR4VzgwR09PaWxxcDFIcVhaYmM0eGl2ZVBNNFJ5ZmJnbmNQRDdnRytOaDlRYnBjQzBmdmhJVUJHClJFYlBjejFRM2JqTTlQVFEzNTBuZEtwSnY1eGdkaVQ5V1BWZHZVakFSTFhFTDR3TUZaMmVlaUJKUkZLVFhCOG4KSGF0cmJsOU41bHg5ck1ma1NBVFBkMnc4NFFnUUl6M2hSOVlJZXJaS2FJNWtibDN1NjQ3dXZsa015SG1xUHZKSQpwRzlYLzlGd1JRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCcnlxWXljVmNQOGdMWUVkRU9FR1JQCml1MVNBeFJyTzVXakN3dmNqY2ZueTVVOUJCV1l4VTRPNnl2WTI1ZnVBb1VTNFlweTc5NmxJZWc5UTlyU2EvRDUKTGY1ZVUvTms2YzMzTnhVTjFGdVhtakJSVlNVNkp6YmRPSnFGbVRYYVhnTXRkMGlPUlRUM2xFbWdra0Y2RVdBZAo2dVFrdVJuQkVQVmFhN2xEZk0zV2V5RVRSS2R1dWlOVTEyR1NyQ015RjBiSWZzZ3lyOENDTWtiUzhXWEROeFlhCldPZmpYcEtTYzVJL1ZBL3hRUzJaUEpzK2F1cTMxaEUzOFhjREVFem1RWFdacS95TVJNNVF5UFR2STAwTEtoR2wKaSt1blZMcWFXR1QvVUx2M3JhTFE1eTNlbnNCSUJmYTdIQ2g2LzFPbHJnbHM0aWV1UGd0c1V4Y3ZNVEMrSXk0dAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: webhook-service
      namespace: crane-system
      path: /mutate-prediction-crane-io-v1alpha1-timeseriesprediction
  failurePolicy: Fail
  name: mprediction.crane.io
  rules:
  - apiGroups:
    - prediction.crane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - TimeSeriesPrediction
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crane-validating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNuRENDQVlRQ0NRQ0xMd1gzK09aUjdUQU5CZ2txaGtpRzl3MEJBUXNGQURBUU1RNHdEQVlEVlFRRERBVmoKY21GdVpUQWVGdzB5TWpBeU1UY3dPRFEyTlRSYUZ3MHpNakF5TVRVd09EUTJOVFJhTUJBeERqQU1CZ05WQkFNTQpCV055WVc1bE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdm84M25rK1I3eHZXCk15eUE5ZHRTa0RQVUxqcjJSMWVuSFlYaW1JNllDa2pxbWJ3QmQ4enFwNVhPWFNOTEVITW55dWpsaFc0bUJUK2YKUDBsZytoMlVzak5XWTFUQzBUTklyYVNSWmFkd0hlQkhaSEsvM2ZwTlllaDBoTXU3QWFUdmpiYWo4VmZyMGk1TwovL0RHVU5HcjR4VzgwR09PaWxxcDFIcVhaYmM0eGl2ZVBNNFJ5ZmJnbmNQRDdnRytOaDlRYnBjQzBmdmhJVUJHClJFYlBjejFRM2JqTTlQVFEzNTBuZEtwSnY1eGdkaVQ5V1BWZHZVakFSTFhFTDR3TUZaMmVlaUJKUkZLVFhCOG4KSGF0cmJsOU41bHg5ck1ma1NBVFBkMnc4NFFnUUl6M2hSOVlJZXJaS2FJNWtibDN1NjQ3dXZsa015SG1xUHZKSQpwRzlYLzlGd1JRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCcnlxWXljVmNQOGdMWUVkRU9FR1JQCml1MVNBeFJyTzVXakN3dmNqY2ZueTVVOUJCV1l4VTRPNnl2WTI1ZnVBb1VTNFlweTc5NmxJZWc5UTlyU2EvRDUKTGY1ZVUvTms2YzMzTnhVTjFGdVhtakJSVlNVNkp6YmRPSnFGbVRYYVhnTXRkMGlPUlRUM2xFbWdra0Y2RVdBZAo2dVFrdVJuQkVQVmFhN2xEZk0zV2V5RVRSS2R1dWlOVTEyR1NyQ015RjBiSWZzZ3lyOENDTWtiUzhXWEROeFlhCldPZmpYcEtTYzVJL1ZBL3hRUzJaUEpzK2F1cTMxaEUzOFhjREVFem1RWFdacS95TVJNNVF5UFR2STAwTEtoR2wKaSt1blZMcWFXR1QvVUx2M3JhTFE1eTNlbnNCSUJmYTdIQ2g2LzFPbHJnbHM0aWV1UGd0c1V4Y3ZNVEMrSXk0dAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: webhook-service
      namespace: crane-system
      path: /validate-prediction-crane-io-v1alpha1-timeseriesprediction
  failurePolicy: Fail
  name: vprediction.crane.io
  rules:
  - apiGroups:
    - prediction.crane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timeseriespredictions
  sideEffects: None
