
apiVersion: v1
kind: Namespace
metadata:
  name: crane-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: crane-agent
  name: crane-agent
  namespace: crane-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crane-agent
  template:
    metadata:
      labels:
        app: crane-agent
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: docker.io/gocrane/crane-agent
          imagePullPolicy: Always
          command:
            - /crane-agent
            - -v=4
          name: crane-agent
          volumeMounts:
            - mountPath: /sys
              name: sys
              readOnly: true
      restartPolicy: Always
      priorityClassName: system-node-critical
      serviceAccount: crane-agent
      volumes:
        - hostPath:
            path: /sys
            type: ""
          name: sys